### ISSUE TITLE
Redirect the "To C or not to C" essay to the article here

### ISSUE THREAD

**Issue by avivace** [gbdev/gbdev.github.io#34]
@ISSOtm , can you please redirect people landing on https://gist.github.com/ISSOtm/4f4d335c3fd258ad0dfc7d4d615409fd to https://gbdev.io/guides/tools.html, currently maintained here? (Don't remove it as some links are currently around)

**Comment by ISSOtm** [comment]
[Done.](https://gist.github.com/ISSOtm/4f4d335c3fd258ad0dfc7d4d615409fd/revisions#diff-429f6e36bddc38aa02e3dff8a53b9ee77b6fedc758c20ec32902cb9036105697)

**Comment by avivace** [comment]
Great, thanks!
