### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/gbdev.github.io#36]
We could use [Prism](https://vuepress.github.io/reference/plugin/prismjs.html) or [shiki](https://vuepress.github.io/reference/plugin/prismjs.html).

**Comment by avivace** [comment]
> We could use [Prism](https://vuepress.github.io/reference/plugin/prismjs.html) or [shiki](https://vuepress.github.io/reference/plugin/prismjs.html).

Those plugin are for Vuepress 2.x. There are alternatives/versions for 1.x but I think we should migrate

**Comment by ISSOtm** [comment]
Ah? Well then, I guess Prism is 1.x's default highlighter, then, as that appears to be what's being used.

**Comment by avivace** [comment]
I installed and enabled Shiki. Imported languages are specified in config.js (https://github.com/gbdev/gbdev.github.io/blob/dev/list/.vuepress/config.js#L4, for now I just added `asm`).
