### ISSUE TITLE
Redirect old URL for "Choosing tools"/"To C or not to C" to new URL

### ISSUE THREAD

**Issue by pinobatch** [gbdev/gbdev.github.io#83]
The previous URL of the article "Choosing tools for Game Boy development" <https://gbdev.io/to_c_or_not_to_c.html> is 404 Not Found instead of the expected 301 Moved Permanently to the current URL <https://gbdev.io/guides/tools.html>. This breaks inbound links.

(<https://www.coranac.com/2008/09/to-c-or-not-to-c/> is still present although unrelated.)

**Comment by avivace** [comment]
Fixed in https://github.com/gbdev/gbdev.github.io/commit/309c692448683b22edbadcc764df562e9a87796b
