### ISSUE TITLE
dead link in guides/tools.html

### ISSUE THREAD

**Issue by SelvinPL** [gbdev/gbdev.github.io#84]
there is a dead link in https://gbdev.io/guides/tools.html#if-you-don-t-know-asm-c-or-c

`online IDE` point to `https://daid.github.io/rgbds-live/` not `https://gbdev.io/rgbds-live/`

**Comment by ISSOtm** [comment]
Fixed in 157a9aac717ff7d76a6e5158249cb74fcebedbfd
